return {
  "nvim-treesitter/nvim-treesitter",
  build = ":TSUpdate",
  event = "VeryLazy",
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "diff",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "glsl",
        "html",
        "http",
        "ini",
        "javascript",
        "json",
        "json5",
        "llvm",
        "lua",
        "make",
        "markdown",
        "markdown_inline",
        "nim",
        "ninja",
        "nix",
        "ocaml",
        "ocaml_interface",
        --"ocamllex",
        "python",
        "regex",
        "ron",
        "rust",
        "scss",
        "toml",
        "typescript",
        "vim",
        "vimdoc",
        "wgsl",
        "xml",
        --"yaml",
        "zig"
      },
      sync_install = false,
      highlight = { enable = true },
      indent = { enable = true }
    })
  end
}
